### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by chinthanika** [chinthanika/creative-writing#3]
### User
- [x] Create user
- [x] Get user by ID
- [x] Get user by attribute
- [x] Delete user

### Entity
- [x] Create entity
- [x] Update entity
- [x] Get entity by ID
- [x] Get entity by attribute
- [x] Get all entities
- [x] Download entities
- [x] Upload images
- [x] Delete entity

### Relation
- [x] Create relation
- [x] Update relation
- [x] Get relation by ID
- [x] Get relation by attribute
- [x] Get all relations
- [x] Delete relation

### Content
- [x] Create content
- [x] Update content
- [x] Get content by ID
- [x] Get content by attribute
- [x] Get all content
- [x] Download content
- [x] Delete content

### Feedback
- [x] Create feedback
- [x] Get all feedback
- [x] Get feedback by ID
- [x] Soft delete feedback

### Response
- [x] Create response
- [x] Get all responses to feedback
- [x] Get response by ID
- [x] Soft delete response

### Conversation
- [x] Create conversation
- [x] Update conversation
- [x] Get conversation history- [x] Get all conversations

### Message
- [x] Create message from user
- [x] Create message from bot

### Goal
- [x] Create goal
- [x] Update goal
- [x] Get goal by ID
- [x] Get goal by attribute
- [x] Get all goals
- [x] Delete goal

### Task

- [x] Create task
- [x] Update task
- [x] Get task by ID
- [x] Get task by attribute
- [x] Get all tasks for a goal
- [x] Delete task

### Progress
- [x] Create progress
- [x] Update progress

### Folder
- [x] Create folder
- [x] Update folder
- [x] Get folder by ID
- [x] Get folder by attribute
- [x] Get all folders
- [x] Delete folder

### Book Collection
- [ ] Get book collection by ID
- [ ] Get book collection by attribute

### Book Details
- [ ] Get details by ID
- [ ] Get details by attribute

### Book Review
- [ ] Get review by ID
- [ ] Get review by attribute

### Template
- [x] Create template
- [x] Update template
- [x] Get template by ID
- [x] Get template by attribute
- [ ] Get all templates
- [x] Delete template

###  Achievement
- [x] Create achievement
- [x] Update achievement
- [x] Get achievement by ID
- [x] Get achievement by attribute
- [ ] Get all achievements
- [x] Delete achievement
